/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkapt.com.ui;

import java.awt.Color;
import java.awt.event.MouseEvent;

/**
 *
 * @author Admin
 */
public class QuanLy extends javax.swing.JFrame {

    private Color transparent;

    /**
     * Creates new form QuanLy
     */
    public QuanLy() {
        initComponents();
        setLocationRelativeTo(null);
        ThongKeUI thongKeUI = new ThongKeUI();
//        deskopMain.removeAll();
        deskopMain.add(thongKeUI).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        pnlQuanLop = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        pnlQuanLySach = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        pnlQuanLyTacGia = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        pnlQuanLyNXB = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        pnlQuanLyViPham = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        pnlPhieuMuon = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnlCaiDat = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnlQuanLyTheLoai = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pnlHome = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnlQuanLySinhVien = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnlThongKe = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        deskopMain = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 51, 255));
        setResizable(false);

        jSplitPane1.setDividerSize(0);

        jPanel5.setBackground(new java.awt.Color(52, 56, 67));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setMinimumSize(new java.awt.Dimension(200, 620));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 520));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlQuanLop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlQuanLop.setOpaque(false);
        pnlQuanLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuanLopMouseClicked(evt);
            }
        });
        pnlQuanLop.setLayout(new java.awt.BorderLayout());

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkapt/com/icon/class.png"))); // NOI18N
        jLabel26.setText("Quản lý lớp             ");
        pnlQuanLop.add(jLabel26, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlQuanLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 50));

        pnlQuanLySach.setBackground(transparent);
        pnlQuanLySach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlQuanLySach.setOpaque(false);
        pnlQuanLySach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuanLySachMouseClicked(evt);
            }
        });
        pnlQuanLySach.setLayout(new java.awt.BorderLayout());

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkapt/com/icon/books-add.png"))); // NOI18N
        jLabel30.setText("Quản lý sách          ");
        pnlQuanLySach.add(jLabel30, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlQuanLySach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 60));

        pnlQuanLyTacGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlQuanLyTacGia.setOpaque(false);
        pnlQuanLyTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuanLyTacGiaMouseClicked(evt);
            }
        });
        pnlQuanLyTacGia.setLayout(new java.awt.BorderLayout());

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkapt/com/icon/writer.png"))); // NOI18N
        jLabel22.setText("Quản lý Tác giả        ");
        pnlQuanLyTacGia.add(jLabel22, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlQuanLyTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 50));

        pnlQuanLyNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlQuanLyNXB.setOpaque(false);
        pnlQuanLyNXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuanLyNXBMouseClicked(evt);
            }
        });
        pnlQuanLyNXB.setLayout(new java.awt.BorderLayout());

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkapt/com/icon/publisher.png"))); // NOI18N
        jLabel24.setText("Quản lý NXB           ");
        pnlQuanLyNXB.add(jLabel24, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlQuanLyNXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 200, 50));

        pnlQuanLyViPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlQuanLyViPham.setOpaque(false);
        pnlQuanLyViPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuanLyViPhamMouseClicked(evt);
            }
        });
        pnlQuanLyViPham.setLayout(new java.awt.BorderLayout());

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkapt/com/icon/warning.png"))); // NOI18N
        jLabel27.setText("Quản lý Vi Phạm       ");
        pnlQuanLyViPham.add(jLabel27, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlQuanLyViPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 200, 50));

        pnlPhieuMuon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlPhieuMuon.setOpaque(false);
        pnlPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPhieuMuonMouseClicked(evt);
            }
        });
        pnlPhieuMuon.setLayout(new java.awt.BorderLayout());

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkapt/com/icon/settings.png"))); // NOI18N
        jLabel12.setText("Quản lý phiếu mượn");
        pnlPhieuMuon.add(jLabel12, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 200, 50));

        pnlCaiDat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCaiDat.setOpaque(false);
        pnlCaiDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCaiDatMouseClicked(evt);
            }
        });
        pnlCaiDat.setLayout(new java.awt.BorderLayout());

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkapt/com/icon/settings.png"))); // NOI18N
        jLabel15.setText("Cài đặt                     ");
        pnlCaiDat.add(jLabel15, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlCaiDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 200, 50));

        pnlQuanLyTheLoai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlQuanLyTheLoai.setOpaque(false);
        pnlQuanLyTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuanLyTheLoaiMouseClicked(evt);
            }
        });
        pnlQuanLyTheLoai.setLayout(new java.awt.BorderLayout());

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkapt/com/icon/ebook.png"))); // NOI18N
        jLabel13.setText("Quản lý Thể loại       ");
        pnlQuanLyTheLoai.add(jLabel13, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlQuanLyTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 50));

        pnlHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlHome.setOpaque(false);
        pnlHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHomeMouseClicked(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkapt/com/icon/Home.png"))); // NOI18N
        pnlHome.add(jLabel11);

        jPanel5.add(pnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        pnlQuanLySinhVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlQuanLySinhVien.setOpaque(false);
        pnlQuanLySinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuanLySinhVienMouseClicked(evt);
            }
        });
        pnlQuanLySinhVien.setLayout(new java.awt.BorderLayout());

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkapt/com/icon/member.png"))); // NOI18N
        jLabel14.setLabelFor(jLabel13);
        jLabel14.setText("Quản lý sinh viên       ");
        pnlQuanLySinhVien.add(jLabel14, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlQuanLySinhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 50));

        pnlThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlThongKe.setOpaque(false);
        pnlThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseClicked(evt);
            }
        });
        pnlThongKe.setLayout(new java.awt.BorderLayout());

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkapt/com/icon/stats.png"))); // NOI18N
        jLabel29.setText("Thống kê báo cáo    ");
        pnlThongKe.add(jLabel29, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 200, 50));

        jSplitPane1.setLeftComponent(jPanel5);

        deskopMain.setBackground(new java.awt.Color(37, 41, 49));
        deskopMain.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        deskopMain.setMinimumSize(new java.awt.Dimension(1154, 754));
        deskopMain.setPreferredSize(new java.awt.Dimension(1154, 754));
        deskopMain.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(deskopMain);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlQuanLySinhVienMouseClicked(MouseEvent evt) {//GEN-FIRST:event_pnlQuanLySinhVienMouseClicked
        // TODO add your handling code here:
        QuanLySinhVien qlsv = new QuanLySinhVien();
        deskopMain.removeAll();
        deskopMain.add(qlsv).setVisible(true);
    }//GEN-LAST:event_pnlQuanLySinhVienMouseClicked

    private void pnlHomeMouseClicked(MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseClicked
        // TODO add your handling code here:
        ThongKeUI tkui = new ThongKeUI();
         deskopMain.removeAll();
        deskopMain.add(tkui).setVisible(true);
    }//GEN-LAST:event_pnlHomeMouseClicked

    private void pnlQuanLopMouseClicked(MouseEvent evt) {//GEN-FIRST:event_pnlQuanLopMouseClicked
        // TODO add your handling code here:
        QuanLyLop qll = new QuanLyLop();
        deskopMain.removeAll();
        deskopMain.add(qll).setVisible(true);
    }//GEN-LAST:event_pnlQuanLopMouseClicked

    private void pnlQuanLySachMouseClicked(MouseEvent evt) {//GEN-FIRST:event_pnlQuanLySachMouseClicked
        // TODO add your handling code here:
        QuanLySach qls =new QuanLySach();
        deskopMain.removeAll();
        deskopMain.add(qls).setVisible(true);
    }//GEN-LAST:event_pnlQuanLySachMouseClicked

    private void pnlQuanLyTacGiaMouseClicked(MouseEvent evt) {//GEN-FIRST:event_pnlQuanLyTacGiaMouseClicked
        // TODO add your handling code here:
        QuanLyTacGia qltg = new QuanLyTacGia();
        deskopMain.removeAll();
        deskopMain.add(qltg).setVisible(true);
    }//GEN-LAST:event_pnlQuanLyTacGiaMouseClicked

    private void pnlQuanLyNXBMouseClicked(MouseEvent evt) {//GEN-FIRST:event_pnlQuanLyNXBMouseClicked
        // TODO add your handling code here:
        QuanLyNXB qlnxb = new QuanLyNXB();
        deskopMain.removeAll();
        deskopMain.add(qlnxb).setVisible(true);
    }//GEN-LAST:event_pnlQuanLyNXBMouseClicked

    private void pnlQuanLyTheLoaiMouseClicked(MouseEvent evt) {//GEN-FIRST:event_pnlQuanLyTheLoaiMouseClicked
        // TODO add your handling code here:
        QuanLyTheLoaiSach qltls = new QuanLyTheLoaiSach();
        deskopMain.removeAll();
        deskopMain.add(qltls).setVisible(true);
    }//GEN-LAST:event_pnlQuanLyTheLoaiMouseClicked

    private void pnlQuanLyViPhamMouseClicked(MouseEvent evt) {//GEN-FIRST:event_pnlQuanLyViPhamMouseClicked
        // TODO add your handling code here:
        QuanLyViPham qlvp = new QuanLyViPham();
        deskopMain.removeAll();
        deskopMain.add(qlvp).setVisible(true);
    }//GEN-LAST:event_pnlQuanLyViPhamMouseClicked

    private void pnlPhieuMuonMouseClicked(MouseEvent evt) {//GEN-FIRST:event_pnlPhieuMuonMouseClicked
        // TODO add your handling code here:
        QuanLyPhieuMuon qlpm = new QuanLyPhieuMuon();
        deskopMain.removeAll();
        deskopMain.add(qlpm).setVisible(true);
    }//GEN-LAST:event_pnlPhieuMuonMouseClicked

    private void pnlCaiDatMouseClicked(MouseEvent evt) {//GEN-FIRST:event_pnlCaiDatMouseClicked
        // TODO add your handling code here:
        CaiDat cd = new CaiDat();
        cd.setVisible(true);
    }//GEN-LAST:event_pnlCaiDatMouseClicked

    private void pnlThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseClicked
        // TODO add your handling code here:
        ThongKeUI thongKeUI = new ThongKeUI();
        deskopMain.removeAll();
        deskopMain.add(thongKeUI).setVisible(true);
    }//GEN-LAST:event_pnlThongKeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskopMain;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlCaiDat;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlPhieuMuon;
    private javax.swing.JPanel pnlQuanLop;
    private javax.swing.JPanel pnlQuanLyNXB;
    private javax.swing.JPanel pnlQuanLySach;
    private javax.swing.JPanel pnlQuanLySinhVien;
    private javax.swing.JPanel pnlQuanLyTacGia;
    private javax.swing.JPanel pnlQuanLyTheLoai;
    private javax.swing.JPanel pnlQuanLyViPham;
    private javax.swing.JPanel pnlThongKe;
    // End of variables declaration//GEN-END:variables
}
